version: "3.9"

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - app_network

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:80"
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      FROM_EMAIL: no-reply@miapp.local

      SECRET_KEY: supersecreto
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60

      DEBUG_DB: "False"
    depends_on:
      - mailhog
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
